sudo: require
language: cpp
compiler:
    - gcc
    - clang
dist: trusty
cache: apt
os: linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
            - gcc-7
            - g++-7
            - clang-5.0

before_install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} ; cd ${DEPS_DIR}
    - |
      CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir -p cmake && travis_retry wget --quiet --no-check-certificate  -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}

before_script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - cmake ..

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd build
    - cmake --build .
    - cmake --build . --target check
