# Doxygen stuff by Jeroen de Bruijn:
# https://gist.github.com/vidavidorra/548ffbcdae99d752da02

sudo: require
language: cpp
compiler:
    - gcc
#   - clang
dist: trusty
cache: apt
os: linux

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: scelta
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/SuperV1234/scelta.git

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz

before_install:
    - sudo apt-get update -q
    - sudo apt-get install clang-5.0 gcc-7 g++-7 -y
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} ; cd ${DEPS_DIR}
    - |
      CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir -p cmake && travis_retry wget --quiet --no-check-certificate  -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}

before_script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi
   # - cd ${TRAVIS_BUILD_DIR}
   # - mkdir build && cd build
   # - cmake -DAUGMENT_TESTS=1 ..

script:
    - cd ${TRAVIS_BUILD_DIR}
   # - cd build
   # - cmake --build .
   # - cmake --build . --target check

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - chmod +x generate-docs.sh
    - ./generate-docs.sh
